nguage: java
jdk:
    - oraclejdk8

script:
    - mvn test
after_success:
    - mvn jacoco:report coveralls:report
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ff7ee6d6992fcb460b82
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

